// Lighting Channels with their assigned GPIO pin numbers
#define LEFT_HEADLIGHT 16
#define RIGHT_HEADLIGHT 13
#define FOG_LIGHTS 3
#define RUNNING_LIGHTS 4
#define INTERIOR_LIGHTS 5
#define LEFT_OUTER_TAILLIGHT 21
#define LEFT_MIDDLE_TAILLIGHT 22
#define LEFT_INNER_TAILLIGHT 23
#define RIGHT_OUTER_TAILLIGHT 26
#define RIGHT_MIDDLE_TAILLIGHT 25
#define RIGHT_INNER_TAILLIGHT 33
#define REVERSE_LIGHTS 12